name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install Minifier
        run: npm install -g html-minifier

      - name: Minify HTML & CSS
        run: |
          html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o index.html.min index.html
          mv index.html.min index.html

      - name: Install HTML Linter
        run: npm install -g htmlhint

      - name: Run HTML Linter
        run: htmlhint index.html || exit 1

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_OCEAN_0AA910703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"
          app_location: "/" 
          api_location: "" 
          output_location: "." 

      - name: Send Slack Notification
        if: always() 
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Deployment Status: ${{ job.status }}",
            "username": "GitHub Actions",
            "icon_emoji": ":rocket:"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_OCEAN_0AA910703 }}
          action: "close"
